server:
  port: 8083
  servlet:
    context-path: /client

spring:
  application:
    name: client
  profiles:
    active:
     - "test"
     
jwt:
  secret: SequenciaDeCaracteresParaAssinarOToken
  expiration: 86400000
   

  
