server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: client
  profiles:
    active:
     - "test"
     
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/registry/eureka


jwt:
  secret: SequenciaDeCaracteresParaAssinarOToken
  expiration: 86400000
   

  
